### ISSUE TITLE
CI: move to GH Actions ?

### ISSUE THREAD

**Issue by jrfnl** [theseer/Autoload#100]
While creating PR #99, I wanted to check that the deprecation notices I mentioned would be shown in CI, only to realize that this repo is still on Travis.

Is that intentional ? Or should the CI of this repo be converted to GH Actions ?

**Comment by theseer** [comment]
No, it's certainly not intentional but rather a sad side effect of neglect :-(

So yes, it certainly should get moved and probably get enhanced as well as there are probably various aspects untested.

On the other hand: I'm actively considering to split this project into three:
- A Library that only contains the magic to create the autoloader lists - probably based on PHP-Parser, and the rendering logic
- A CLI Wrapper around that library
- A new tool to build phars - under the phar.io umbrella - that uses the library for the autoloader, adds proper manifests and signatures

So, while it's appreciated to get CI back up on GH actions, there shouldn't be tooo much energy be spent on doing so.

**Comment by jrfnl** [comment]
@theseer Well, if sticking with the current workflow as run on Travis would be okay, than converting that to GH Actions shouldn't take much effort. I'd be happy to take a look in a little.
