### ISSUE TITLE
Add option to handle duplicate declarations across multiple files

### ISSUE THREAD

**Issue by sebastianbergmann** [theseer/Autoload#76]
At the moment, `--tolerant` only ignores duplicate declarations of classes, interfaces, and traits that occur in the same source file.

Some code bases have duplicate declarations of classes, interfaces, and traits that do not occur in the same source file. Currently, PHPAB errors out on a code base like that. It would be nice to have a separate option that handles a situation like that by using the first source file found when multiple source files exist that declare a unit of code of the same name.

**Comment by theseer** [comment]
While of course it is possible to add the desired behaviour into PHPAB, I'm not convinced that the resulting map would be useful:

* In case the code base implements some logic to load either definition, chances are that neither definition would be included/required using autoload. The entry in the map is thus pointless. 

* If the duplication exists because the developers were unaware of having that potential conflict, using the first match may or may not load the originally anticipated copy. That may work if the two copies are actually identical but may not work if they represent different versions of the same class.

* If the load order would be based on the include path, using the first entry may also be off. With same side effects as above.


In cases where custom logic is applied to require a specific version, having a `--skip-duplicates` switch might be useful. But overall, there is no way to make this work reliably if the two different versions are to be autoloaded with a map.

Thoughts?

**Comment by sebastianbergmann** [comment]
Makes sense.
