### ISSUE TITLE
symfony/event-dispatcher Duplicate definitions of the following unit(s) found

### ISSUE THREAD

**Issue by DjThossi** [theseer/Autoload#87]
Hello Arne,

we're trying to build our own coding standard as a phar file. This is currently failing due to the following error:

```
$ tools/phpab --all --phar --alias cs.phar --gzip --exclude \*tests\* --output build/phar/cs-${version}.phar --template phar/templates/bootstrap.php.in --basedir . ./src ./vendor

 phpab 1.25.6 - Copyright (C) 2009 - 2019 by Arne Blankerts and Contributors
 
 Scanning directory ./src
 Scanning directory ./vendor
 Duplicate (potentially conditional) definitions of the following unit(s) found:
 
     Unit(s): symfony\contracts\eventdispatcher\eventdispatcherinterface
     File: /var/www/vendor/symfony/event-dispatcher-contracts/EventDispatcherInterface.php
```

To make this easier I could nail the issue down to the composer dependency `symfony/event-dispatcher`. Here a simplified version of the composer.json which causes the problem.  

```
{
    "require": {
        "php": ">=7.3",
        "symfony/event-dispatcher": "^4.3"
    }
}
```

**Comment by theseer** [comment]
`phpab` is correct: The class `Symfony\Contracts\EventDispatcher\Event` is defined twice but "luckily" conditionally in the same file - since only one file is shown in the error message.

Assuming you cannot fix that - I have still no idea why people do that, there are so many nicer options ;) - and given it's in the same file, you can use `--tolerant` as a switch for `phpab`.

**Comment by DjThossi** [comment]
Thank you very much for your feedback. You're right I overlooked the `--tolerant` option. Now everything works again.
