### ISSUE TITLE
Adopt, if needed, to PHP 8's T_NAME_FULLY_QUALIFIED, T_NAME_RELATIVE, and T_NAME_QUALIFIED tokens

### ISSUE THREAD

**Issue by sebastianbergmann** [theseer/Autoload#95]
* https://wiki.php.net/rfc/namespaced_names_as_token
* https://github.com/php/php-src/pull/5827

**Comment by PerryRylance** [comment]
I'm having issues using this library on a fresh install of XAMPP with PHP 8.0.0

The library is unable to parse this line

`class Settings implements \IteratorAggregate`

The message reports `due to parse errors: Parse error while trying to process class definition (unexpected token in name).`

Could this be related?

Removing the `implements` solves the issue, but obviously it's not ideal for my application

**Comment by PerryRylance** [comment]
I can confirm that updating to 1.26.0 solves this issue, assuming I'm referring to the same thing here

**Comment by theseer** [comment]
Yes, to use with PHP 8.0 - or later - you need at least 1.26.0 because of the changed tokenizing.
